// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ditexrwjqoziegmozhda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpdGV4cndqcW96aWVnbW96aGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTE4OTUsImV4cCI6MjA3MTY4Nzg5NX0.ea8DEmAowbZ-lZgfmTaW2QpblWhXTR4O9v5JEPgxF6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});